export const GET_CATEGORY ='GET_CATEGORY';
export const ADD_CATEGORY ='ADD_CATEGORY';
export const SOFTDEL_CATEGORY ='SOFTDEL_CATEGORY';
export const LOADING_ITEMS ='LOADING_ITEMS';
export const GET_EXPENSE ='GET_EXPENSE';
export const ADD_EXPENSE ='ADD_EXPENSE';
export const SOFTDELETE_EXPENSE ='SOFTDELETE_EXPENSE';